import nl.woodmanict.koos.parsers.KoosTeamParser;
import nl.woodmanict.koos.parsers.KoosScheduleParser;
import nl.woodmanict.koos.model.Team;
import nl.woodmanict.koos.dao.TeamDao;
import nl.woodmanict.koos.dao.TeamDaoImpl;

import java.util.List;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
  private static TeamDao teamDao = TeamDaoImpl.getInstance();

  private static void printTeams() {
    System.out.println("Teams:");

    teamDao.getTeams().stream().forEach(System.out::println);
  }

    public static void main(String[] args) {

        try {
          final String path = App.class.getResource("KoosCompetitie2017.xlsx").getPath();
          KoosTeamParser teamParser = new KoosTeamParser(path);

          teamParser.parseTeams(teamDao::addTeam);

          printTeams();

          KoosScheduleParser koosScheduleParser = new KoosScheduleParser(path);
          koosScheduleParser.parseSchedule(System.out::println);
      } catch (Exception e) {
        System.err.println(e.getMessage());
        e.printStackTrace();
      }
    }
}
